# Generated by Django 3.1.3 on 2020-12-03 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20201203_2014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_image',
            new_name='article_photo',
        ),
    ]
